[package]
name = "rust-ml-benchmark"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_benchmark"
path = "rust_benchmark.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] } 